services:
  - type: web
    name: possim
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: BLOCK_INTERVAL_MINUTES
        value: "2"
